[package]
name = "rlife"
version = "0.0.5"
authors = ["CYS Eisha <chenyensu0@gmail.com>"]
description = "A life library written in Rust."
license = "LGPLv3"
repository = "https://github.com/Kagamihime/rlife.git"

[dependencies]
rand = "0.3"
